#!/bin/bash
user="bhar9988"
logtag=".pbsserver"
regexstr="[0-9]+(?=${logtag})"
if [ -z "$1" ]; then
  jobid=$(qstat | tac | grep $user | grep -m1 -P ${regexstr} -o)
else
  jobid=$1
fi
logdir=$HOME/jobs/
logext=".log"
logfile="${logdir}${jobid}${logtag}${logext}"
echo "Monitoring ${logfile}"
tail -f $logfile
